
setw -g mode-keys vi

# Use vim keys to move between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -s escape-time 0
bind b last-window

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

set -g status-position top
set -g mouse on
set -g status-right ""
set -g status-style fg=colour8,bg=black
set -g status-left-length 20
set -g status-right-length 50

# set status bar background to black
# set -g status-style bg=black
# optional: set the text color
# set -g status-style fg=white

set -g status-justify centre
