
# so that there's no lag when pressing <ESC> in vim
set -s escape-time 0

setw -g mode-keys vi
bind b last-window

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Status bar
set -g status on
set -g status-style "bg=#1f1f28,fg=#c0c0c0"

# Left and right status
set -g status-left-length 40
set -g status-right-length 100

set -g status-justify centre
set -g status-left "#[fg=#61afef,bold] #S "
set -g status-right ""

setw -g window-status-current-style "bg=#1f1f28,fg=#ffffff"
setw -g window-status-style "bg=#1f1f28,fg=#828997"
