
# so that there's no lag when pressing <ESC> in vim
set -s escape-time 0

set -g base-index 1
setw -g pane-base-index 1

setw -g mode-keys vi
set -g mouse on
bind b last-window
bind h new-window -c "#{pane_current_path}"

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Status bar
set -g status on
set -g status-justify centre
set-option -g status-position top
set -g status-style "bg=default,fg=#c0c0c0"

# Left and right status
set -g status-left ""
set -g status-left-length 40
set -g status-right ""
set -g status-right-length 100

# Current window 7aa2f7
set -g window-status-current-format "#[fg=#7aa2f7,bg=default,bold] [#I:#W] "
setw -g window-status-current-style "bg=default,fg=#ffffff"

# which window? The last active one?
setw -g window-status-style "bg=default,fg=#828997"
# Last active window (we fake it visually)
set -g window-status-format "#[fg=#c0caf5] #{?window_last_flag,<#I:#W>, #I:#W } "

# For command prompt (e.g. :)
set -g message-command-style "bg=default,fg=#c0caf5"

# For general messages (optional, but related)
set -g message-style "bg=default,fg=#c0caf5"

# Use vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
